ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/drorbr1/bramly'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readiness:
  path: /health/liveliness
  initialDelaySeconds: 1
  timeoutSeconds: 1
  periodSeconds: 10 # the abount of time to wait between checks
  successThreshold: 1 # count to decalre seccessfull 
  failureThreshold: 3 # count to decalre failure
liveness:
  path: /health/liveliness
  initialDelaySeconds: 1
  timeoutSeconds: 1
  periodSeconds: 10 # the abount of time to wait between checks
  successThreshold: 1 # count to decalre seccessfull 
  failureThreshold: 3 # count to decalre failure
volume:
  mount:
  path: /tmp/html